const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const dir=path.resolve('outputs/App_02/dist');const scripts=[...fs.readFileSync(dir+'/index.html','utf8').matchAll(/<script src="([^"]+)"/g)].map(m=>m[1]);let saved={},handlers={},downloads=[],registered;const nodes={};const node=s=>nodes[s]??={innerHTML:'',textContent:'',focus(){},scrollIntoView(){},append(){},remove(){},click(){if(this.download)downloads.push(this.download)}};
const ctx={console,Date,Object,JSON,String,Number,Error,SyntaxError,Promise,Blob,Set,setTimeout:()=>1,clearTimeout(){},URL:{createObjectURL:()=>'',revokeObjectURL(){}},navigator:{},location:{hash:''},localStorage:{getItem:k=>saved[k],setItem:(k,v)=>saved[k]=v},window:{addEventListener(){},scrollTo(){},print(){}},document:{querySelector:node,querySelectorAll:()=>[],addEventListener:(e,fn)=>handlers[e]=fn,createElement:()=>node('download'),body:{append(){},classList:{toggle(){}}},modelContext:{registerTool:t=>registered=t}}};vm.createContext(ctx);for(const f of scripts){new vm.Script(fs.readFileSync(dir+'/'+f,'utf8'),{filename:f}).runInContext(ctx)}
const run=s=>vm.runInContext(s,ctx);
for(const route of run('Object.keys(routes)')){ctx.location.hash='#'+route;run('render()');assert(node('#main').innerHTML.length>80);for(const m of node('#main').innerHTML.matchAll(/(?:href|src)="(assets\/[^"]+)"/g)){assert(fs.existsSync(path.join(dir,m[1].split('#')[0])),route+': '+m[1]);}}
assert.equal(run('Object.keys(MODULES).length'),12);
const v1=run("({format:'ki-horizonte',version:1,fields:Object.fromEntries(Object.keys(baseFields).map(k=>[k,k==='titel'?'Altes Vorhaben':''])),updatedAt:null})");ctx.legacy=v1;assert.equal(run('validate(legacy).fields.titel'),'Altes Vorhaben');assert.equal(run('validate(legacy).version'),2);
run("state.fields.titel='Neuer Stand';state.fields['rueckmeldung__weiter']='Das behalten wir.';save();exportFile()");assert(downloads.length===1);assert.equal(run('validate(JSON.parse(JSON.stringify(state))).fields.rueckmeldung__weiter'),'Das behalten wir.');
const payload=JSON.parse(fs.readFileSync('outputs/App_02/Begleitung_NICHT_IN_APP/C02_02.json','utf8'));ctx.payload=payload;assert.equal(run('validateMaterial(payload).module'),'lernen-verstehen');assert.throws(()=>run("validateMaterial({...payload,module:'pruefen-a'})"));assert.throws(()=>run("validate({format:'ki-horizonte',version:2,fields:{}})"));
run("state.fields['rueckmeldung__weiter']='<script>alert(1)</script>'");assert(run("moduleView('rueckmeldung')").includes('&lt;script&gt;'));
(async()=>{ctx.location.hash='#lernen-verstehen';run('render()');const json=JSON.stringify(payload);await handlers.change({target:{id:'material-import',files:[{size:json.length,text:async()=>json}],value:'x'}});assert(node('#material-preview').innerHTML.includes('Erhaltenes Material'));node('#apply-material').onclick();assert.equal(run('state.materials.length'),1);run("state.materialNotes.C02_02='Mein späterer Gedanke'");assert.equal(run('validate(JSON.parse(JSON.stringify(state))).materialNotes.C02_02'),'Mein späterer Gedanke');
const stateJson=run('JSON.stringify(state)');ctx.location.hash='#speicher';run('render()');await handlers.change({target:{id:'import',files:[{size:stateJson.length,text:async()=>stateJson}],value:'x'}});node('#apply-import').onclick();assert.equal(run('state.materials.length'),1);
registered.execute({view:'pruefen-b'});assert.equal(ctx.location.hash,'pruefen-b');assert.throws(()=>registered.execute({view:'__proto__'}));ctx.location.hash='#constructor';run('render()');assert(node('#main').innerHTML.includes('Welchen Horizont'));
// All participant assets are independent of the coordinator package.
for(const f of scripts)assert(!fs.readFileSync(dir+'/'+f,'utf8').includes('Begleitung_NICHT_IN_APP'));
console.log('PASS: '+scripts.length+' separate scripts, '+run('Object.keys(routes).length')+' views, all file references, legacy migration, cross-area persistence, export/import, coach material import, invalid input rejection, escaping, protected-material separation and navigation tool logic.');})();
